"""Add passkeys table and update users for passwordless auth

Revision ID: 5984e822c0db
Revises: ebd54edd0cf9
Create Date: 2026-01-30 10:20:18.076342

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5984e822c0db"
down_revision: Union[str, Sequence[str], None] = "ebd54edd0cf9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "passkeys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("credential_id", sa.LargeBinary(), nullable=False),
        sa.Column("public_key", sa.LargeBinary(), nullable=False),
        sa.Column("sign_count", sa.Integer(), nullable=False),
        sa.Column("device_type", sa.String(length=20), nullable=False),
        sa.Column("backed_up", sa.Boolean(), nullable=False),
        sa.Column("transports", sa.Text(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_passkeys_credential_id"), "passkeys", ["credential_id"], unique=True
    )
    op.create_index(op.f("ix_passkeys_id"), "passkeys", ["id"], unique=False)
    op.create_index(op.f("ix_passkeys_user_id"), "passkeys", ["user_id"], unique=False)
    op.add_column(
        "users", sa.Column("display_name", sa.String(length=100), nullable=True)
    )
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("hashed_password", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("users", "display_name")
    op.drop_index(op.f("ix_passkeys_user_id"), table_name="passkeys")
    op.drop_index(op.f("ix_passkeys_id"), table_name="passkeys")
    op.drop_index(op.f("ix_passkeys_credential_id"), table_name="passkeys")
    op.drop_table("passkeys")
    # ### end Alembic commands ###
